[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
profile = 'black'
known_third_party = []

[tool.mypy]
plugins = 'pydantic.mypy'
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.check-manifest]
ignore = [
    ".pre-commit-config.yaml",
    ".banditrc",
    ".flake8",
    ".vscode/*",
    "*.md",
    "debian/*",
    "requirements*",
    "start.sh",
    "tox.ini",
    "mypy.ini",
    "extras*",
    "config-sample.toml",
    ".DS_Store",
    "pc",
    ]
